apiVersion: v1
kind: Service
metadata:
  name: data_container-service
  labels:
    app: data_container
  namespace: myapps
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: data_container